# Homebrew info

APP_TITLE       := 3ds1010
APP_DESCRIPTION := Port of the 1010! mobile game to the 3ds
APP_AUTHOR      := LiquidFenrir

ICON            := resources/icon.png

# CIA info

PRODUCT_CODE := CTR-P-TETE
UNIQUE_ID    := 0x3d170

BANNER_AUDIO := resources/audio.wav
BANNER_IMAGE := resources/banner.png

# Directories

BINNAME := 3ds1010
BINDIR  := out
BUILD   := build
SOURCES := source
ROMFS   := romfs

# Build info

LIBRARIES := citro3d ctru m
